// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace WWTravelClubDB.Optimization
{
    partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var destination = DestinationEntityType.Create(this);
            var package = PackageEntityType.Create(this);

            PackageEntityType.CreateForeignKey1(package, destination);

            DestinationEntityType.CreateAnnotations(destination);
            PackageEntityType.CreateAnnotations(package);

            AddAnnotation("ProductVersion", "6.0.0-rc.1.21452.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
